name: Enonic CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build, Test and Deploy app
        uses: docker://enonic/enonic-ci:7.2
        with:
          key: ${{ runner.os }}-v1
          args: bash -c "enonic project build"